version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.5-browsers
      - image: circleci/postgres:9.6.9-alpine
        environment:
          POSTGRES_DB: ci
          POSTGRES_PASSWORD: ci
          POSTGRES_USER: ci
    environment:
      ENV_FOR_DYNACONF: ci
      PIPENV_VENV_IN_PROJECT: 1
    steps:
      - checkout

      - run:
          name: (Waiting for Postgres to be ready)
          command: |
            make wait-for-db
      - restore_cache:
          keys:
            - cc-venv-{{ checksum "Pipfile.lock" }}
      - run:
          name: Setting up virtualenv
          command: |
            sudo pip install pipenv
            make venv-dev
      - save_cache:
          key: cc-venv-{{ checksum "Pipfile.lock" }}
          paths:
            - ./.venv/
      - restore_cache:
          keys:
            - cc-selenium-{{ checksum "./.circleci/selenium.link" }}
      - run:
          name: Setting up Selenium
          command: |
            curl -O $(cat ./.circleci/selenium.link)
            mv selenium-*.jar selenium.jar
      - save_cache:
          key: cc-selenium-{{ checksum "./.circleci/selenium.link" }}
          paths:
            - ./selenium.jar
      - run:
          name: Performing release steps
          command: |
            make initdb release
      - run:
          name: (Running Selenium)
          command: java -jar selenium.jar -log selenium.log
          background: true
      - run:
          name: (Running Local Web Server)
          command: make run
          background: true
      - run:
          name: Performing Tests
          command: |
            make test

workflows:
  main:
    jobs:
      - build-and-test