default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  SECRET_KEY: ""
  SITE_ID: 0
  TIME_ZONE: ""
  DEBUG: true
  API_KEY: ""
  WEB_CONCURRENCY: 0
  PORT: -1
  DIRS_RESOURCES:
    - config
  DIRS_SOURCES:
    - src
    - utils
  DIRS_EXCLUDED:
    - .idea
    - .pytest_cache
    - .tests_artifacts
  DIRS_TEMPLATES: [ ]
  MODE_DEBUG: true
  MODE_PROFILING: false
  VENV_SYNTHETIC: false
  PROJECT_NAME: ""
  TEMPLATE_ENGINE: "Django"
  GITHUB_CLIENT_ID: ""
  GITHUB_SECRET: ""
  GITHUB_ACCESS_TOKEN: ""


development:
  SITE_ID: 1
  TIME_ZONE: "Europe/Minsk"
  DEBUG: true
  PORT: 8000

ci:
  PORT: 8000
  SECRET_KEY: "1"
  WEB_CONCURRENCY: 2

test:
  SITE_ID: 1
  TIME_ZONE: "UTC"
  DEBUG: true
