default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  SECRET_KEY: ""
  SITE_ID: 0
  TIME_ZONE: ""
  DEBUG: true
  API_KEY: ""

development:
  SITE_ID: 1
  TIME_ZONE: "Europe/Minsk"
  DEBUG: true

test:
  SITE_ID: 1
  TIME_ZONE: "UTC"
  DEBUG: true
