default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  SECRET_KEY: ""
  SITE_ID: 0
  TIME_ZONE: ""
  DEBUG: true
  HOST: ""
  API_KEY: ""
  WEB_CONCURRENCY: 0
  PORT: -1
  DIRS_RESOURCES:
    - config
  DIRS_SOURCES:
    - src
    - src/scripts
  DIRS_EXCLUDED:
    - .idea
    - .pytest_cache
    - .tests_artifacts
  DIRS_TEMPLATES: [ ]
  MODE_DEBUG: true
  MODE_PROFILING: false
  VENV_SYNTHETIC: false
  PROJECT_NAME: ""
  TEMPLATE_ENGINE: "Django"
  GITHUB_CLIENT_ID: ""
  GITHUB_SECRET: ""
  GITHUB_ACCESS_TOKEN: ""
  HEROKU_API_TOKEN: ""
  HEROKU_API_APP_ID: ""
  SENTRY_DSN: ""


development:
  SITE_ID: 1
  TIME_ZONE: "Europe/Minsk"
  DEBUG: true
  PORT: 8000
  HOST: "localhost"

ci:
  HOST: "localhost"
  PORT: 8000
  SECRET_KEY: "1"
  WEB_CONCURRENCY: 2
  DATABASE_URL: "postgresql://ci:ci@localhost:5432/ci?sslmode=disable"

test:
  SITE_ID: 1
  TIME_ZONE: "UTC"
  DEBUG: true

docker:
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "Europe/Minsk"
  DATABASE_URL: "postgresql://anastasiyataranava:1@labels-db:5432/labels"

heroku:
  ALLOWED_HOSTS:
    - helper-github.herokuapp.com
  MODE_DEBUG: false
  VENV_SYNTHETIC: 1
  SECRET_KEY: "1"